#env:
# CIRRUS_CLONE_DEPTH: "1"
# BUILD_HOSTNAME: "cirrus-ci.org"
# RCLONECONFIG_DRIVE: "ENCRYPTED[!665ad41f512cfd46b1b49ad1f69efec8e0d9c5ada14986fac1730369e962c30a9e230a884ce298219adf2315e53f4da7!]"
# TG_TOKEN: "ENCRYPTED[!b5963522fdf5357a4832c52ab3f4f6b5c9f6d208423667e57fc69bdfae18a616bbf623a018a47044b614760e2999654c!]"
# TG_CHAT_ID: "ENCRYPTED[!56d905a58be9331f431ceabbbfd176027699669d96dce3fa27db4a97792a98cf95b8c958aa93022f69af2df353e40f4b!]"
# WORKDIR: "/tmp"
# EMAIL: "ENCRYPTED[!01fba28bbd1a32c72be0bf6004ddf11ed3143e2e0fed84728ef33f5757b73bd6b566794150cff57956dd345f8ec07739!]"
  
env:
    MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
    MANIFEST_BRANCH: twrp-12.1
    DEVICE: gauguin
    DT_LINK: https://github.com/Seifood/device_xiaomi_gauguin-TWRP
    DT_PATH: device/xiaomi/gauguin
    LUNCH_TARGET: twrp
    TARGET: bootimage

task:
  name: "Building recovery"
  timeout_in: 240m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G
  
  Sync_script:
      - mkdir ~/twrp
      - cd ~/twrp
      - repo init --depth=1 -u $MANIFEST -b $MANIFEST_BRANCH
      - repo sync
      - git clone $DT_LINK $DT_PATH

  Build_script:
      - cd ~/twrp
      - export ALLOW_MISSING_DEPENDENCIES=true
      - export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
      - export LC_ALL="C"
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch twrp_selene-eng
      - mka $TARGET
     
  Upload_script:
      - cd ~/twrp
      - cd out/target/product/$DEVICE
      - ls -lh
      - curl -sL https://git.io/file-transfer | sh 
      - ./transfer gof boot.img
