env:
  CIRRUS_CLONE_DEPTH: "1"
  BUILD_HOSTNAME: "cirrus-ci.org"
  BUILDKITE_AGENT_TOKEN: "ENCRYPTED[!77b9fdb8028984a29b149a770a718698c99bca558c061a0b41c113e8e7077396b665dd27390036ee99d9fb2795e23e23!]"
# RCLONECONFIG_DRIVE: "ENCRYPTED[!665ad41f512cfd46b1b49ad1f69efec8e0d9c5ada14986fac1730369e962c30a9e230a884ce298219adf2315e53f4da7!]"
# TG_TOKEN: "ENCRYPTED[!b5963522fdf5357a4832c52ab3f4f6b5c9f6d208423667e57fc69bdfae18a616bbf623a018a47044b614760e2999654c!]"
# TG_CHAT_ID: "ENCRYPTED[!56d905a58be9331f431ceabbbfd176027699669d96dce3fa27db4a97792a98cf95b8c958aa93022f69af2df353e40f4b!]"
# WORKDIR: "/tmp"
#  EMAIL: "ENCRYPTED[!01fba28bbd1a32c72be0bf6004ddf11ed3143e2e0fed84728ef33f5757b73bd6b566794150cff57956dd345f8ec07739!]"
  
task:
  name: "Build"
  timeout_in: 180m
  container:
      image: buildkite/agent:ubuntu
      cpu: 8
      memory: 32G
        
  Size-file_data:
      - df -h
#     - cd ~/work
#     - repo init --depth=1 --no-repo-verify -u https://github.com/Evolution-X/manifest -b tiramisu -g default,-mips,-darwin,-notdefault
#     - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
#     - git clone https://github.com/Evolution-X-Devices/device_xiaomi_lavender device/xiaomi/lavender
#     - git clone https://github.com/Evolution-X-Devices/kernel_xiaomi_lavender kernel/xiaomi/lavender
#     - git clone https://github.com/Evolution-X-Devices/vendor_xiaomi_lavender vendor/xiaomi/lavender
#     - git clone https://github.com/samsung-m11q/android_kernel_samsung_m11q kernel/samsung/m11q
#     - git clone https://github.com/Atharv-Supremacy/android_vendor_samsung_m11q vendor/samsung/m11q
#     - git clone https://github.com/Atharv-Supremacy/android_device_samsung_m11q device/samsung/m11q
#     - git clone https://github.com/LineageOS/android_device_samsung_slsi_sepolicy -b lineage-18.1 device/samsung_slsi/sepolicy
#     - git clone https://github.com/LineageOS/android_hardware_samsung -b lineage-18.1 hardware/samsung

  List_data:
      - ls -a
#     - . build/envsetup.sh
#     - lunch evolution_lavender-userdebug
#     - mka evolution
     
  Free_data:
      - free -t -h
#     - cd out/target/product/lavender
#     - curl -sL https://git.io/file-transfer | sh
#     - ./transfer gof *.zip
